# Generated by Django 3.0.7 on 2021-03-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekersocialdetails',
            old_name='linkden',
            new_name='twitter',
        ),
    ]
