# Generated by Django 3.0.7 on 2021-03-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210327_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekeradditionaldetails',
            name='work_experience',
        ),
    ]
