# Generated by Django 3.0.7 on 2021-03-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210327_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekeradditionaldetails',
            name='work_experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
