# Generated by Django 3.2 on 2021-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210406_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
