# Generated by Django 3.2 on 2021-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210412_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
