# Generated by Django 3.2 on 2021-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210417_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekeradditionaldetails',
            name='preferred_job_category',
        ),
        migrations.AddField(
            model_name='seeker',
            name='preferred_job_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
