# Generated by Django 3.2 on 2021-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210503_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seekeradditionaldetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seekersocialdetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
