# Generated by Django 3.2 on 2021-05-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='is_verivied',
            new_name='is_verified',
        ),
    ]
