# Generated by Django 3.0.7 on 2021-03-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='usercv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
