# Generated by Django 3.2 on 2021-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210406_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
