# Generated by Django 3.0.7 on 2021-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('feedback', models.CharField(max_length=1050, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback/')),
            ],
        ),
    ]
