# Generated by Django 3.2 on 2021-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0002_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=1050, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback/')),
            ],
        ),
    ]
